PATCH_IDE=FALSE
PATCH_SD=FALSE
PATCH_FULL_ACCESS=TRUE
PATCH_INFO=TRUE
PATCH_UNSUPPORTED_OSFILE=TRUE
PATCH_PRESERVE_CONTEXT=FALSE
TEST_SHIFT=FALSE
INCLUDE_FLOPPY=FALSE
SHADOW_SCREEN=FALSE

ABSWS=&0E00
        
include "adfs150.asm"
