PATCH_IDE=TRUE
PATCH_SD=FALSE
PATCH_FULL_ACCESS=TRUE
PATCH_INFO=TRUE
PATCH_UNSUPPORTED_OSFILE=TRUE
PATCH_PRESERVE_CONTEXT=TRUE
TEST_SHIFT=TRUE
INCLUDE_FLOPPY=TRUE
SHADOW_SCREEN=TRUE
        
ABSWS=&C000
        
include "adfs150.asm"
